"""add selected_theme to user

Revision ID: ebede9e8d9e0
Revises: ce616888be5b
Create Date: 2026-07-21 13:12:35.505906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebede9e8d9e0'
down_revision: Union[str, Sequence[str], None] = 'ce616888be5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_theme', sa.String(length=64), server_default='theme_classic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'selected_theme')
    # ### end Alembic commands ###
